### ISSUE TITLE
animation bumps episode list

### ISSUE THREAD

**Issue by amcquade** [amcquade/quick-feed#18]
the episode list is bumped down by the fetch animation if you search for additional feeds

**Comment by larryschirmer** [comment]
hi, I'd like to work on this issue if that's ok? How do you feel about having the loading animation in a modal centered over the screen?
![loading_modal_mock](https://user-images.githubusercontent.com/1797536/67257435-eb645a80-f459-11e9-8d67-a9ee93f9e89e.jpg)

**Comment by amcquade** [comment]
@larryschirmer yes this is what im looking for!

**Comment by larryschirmer** [comment]
@amcquade great, I'll get started on a PR then. Happy Hacktober!
